### ISSUE TITLE
`created_ts` and `updated_ts` are automatic

### ISSUE THREAD

**Issue by ggallen** [kubearchive/kubearchive#171]
I still don't like the field names for timestamps, particularly `cluster_deleted_ts`.  I don't know what makes this field so different that it has to have "cluster" in it. I see this in the documentation:
```
created_ts: Time when KubeArchive received the resource for the first time.
updated_ts: Last time KubeArchive received an update for the resource.
cluster_deleted_ts: Timestamp when KubeArchive deleted the resource from the cluster.
```
Why not just `deleted_ts` again? Shouldn't this just be the "Time when KubeArchive received the delete event"? Or "Time when KubeArchive submitted the deletion of the resource"?

**Comment by maruiz93** [comment]
I don't think we should name the field `deleted_ts`.

It is quite a standardize thing to include in the DB tables the fields `created_at` and `updated_at` (that relates to our `created_ts` and `updated_ts` fields). 
The meaning of these fields are:

* created_at --> When the record was first inserted in the table
* updated_at --> Last time the record is updated in the table

It is quite common to include these fields in all the tables of a database, because they are metadata of the record per se, and not related to the business logic.

There is no `deleted_at` because following the logic of the other timestamps, that would mean "When the record is deleted from the table" and that makes no sense if the record is still there.

In our case we want to have:

*cluster_deleted_ts --> When kubearchive prune the resource from etcd

If you don't like `cluster_deleted_ts` we can change it to a different one, maybe `etcd_deleted_ts` or `etcd_prune_ts` but I will encourage not to use `deleted_ts` because that will be confusing giving the standardize usage of `created_at` and `updated_at` standardize usage as metadata for the record in the tables.

**Comment by maruiz93** [comment]
Other things to consider are:

* In the future we may want to address the actual removal of old records in the kubearchive database. We should be carefull of the word "delete" either providing context of "what we delete where" or by using different words like prune/delete, being prune the removal of resources from etcd to get it cleaned and delete the complete removal of the resources

* I've also seen triggers defined in the database like [these ones](https://medium.com/@alexishevia/automatic-timestamps-with-postgresql-8a5fc499d887) to automatically fill the `updated_at` and `created_at` fields in the DB and not having to set them manually. As I see it, this also helps stating the different nature of the fields (`updated_ts` `created_ts`) and `cluster_deleted_ts` because the last one can't be automated based what happens with the record in relation with the table.

**Comment by skoved** [comment]
I have been treating `created_ts` and `updated_ts` as the timestamps for when resource was created and updated by kubernetes (these values can be obtained from the cloudevents from ApiServerSource). If that was not the intention of those fields, it would be easy to change what data the sink writes for them

**Comment by maruiz93** [comment]
When I [suggested](https://github.com/kubearchive/kubearchive/pull/44#discussion_r1623406318) adding the `created_ts` and `updated_ts` I was thinking of the standard usage of `created_at` and `updated_at` that I described earlier, but I wasn't aware that we were using them in a different way.

Then I guess that we can turn this conversation to decide the following:

* Do we want to have fields with the meaning of "When was this record first inserted" and "When was this record lastly updated" --> My vote is yes
* Do we want to also have fields with TS of when the resources where created and updated in etcd? --> If I understand correctly we already have those inside the JSON field with the resource. If that's the case I would say that we don't need them duplicated (for now).

**Comment by ggallen** [comment]
> Do we want to have fields with the meaning of "When was this record first
> inserted" and "When was this record lastly updated" 

I'm OK with this as well, but these fields should *only* be updated using a trigger.

> Do we want to also have fields with TS of when the resources where created and updated in etcd?

I'm OK with waiting on this as well. I think there is a use-case for selecting resources by some time range, so these fields may be valuable then (if we can't get them from the JSON efficiently).
