### ISSUE TITLE
The `resource.uuid` field should be the primary key

### ISSUE THREAD

**Issue by ggallen** [kubearchive/kubearchive#172]
The field `resource.cluster_uuid` should be renamed to `uuid` and should be the primary key field for the table. The `resource.id` field can then be deleted.

And (optionally, pending discussion), the `cluster_name` field should be removed.

**Comment by rh-hemartin** [comment]
I think renaming `cluster_uuid` to `uuid` does not make sense if we want to keep `cluster_name`.

But if I understood correctly, I agree that we should use the `uid` of the resource as key of the table, instead of an auto-generated id by the database. Also it does make sense calling it `uuid` or `uid` instead of `id` to clearly convey that is the resource uid.

**Comment by ggallen** [comment]
No, `uuid` is the resource's `uuid`, taken from the metadata. Just like `name`.

**Comment by rh-hemartin** [comment]
We agreed on creating a `uid` field that is `metadata.uid` from the resource and that is used as key identifier of the table. @skoved will incorporate it in #170

**Comment by ggallen** [comment]
> We agreed on creating a `uid` field

This should be `uuid`, not `uid`.

**Comment by skoved** [comment]
I can go either way. kubernetes calls it `uid`, even though it is a uuid, but we don't have to follow their naming convention

**Comment by ggallen** [comment]
It's type is `uuid` in postgres.  I think we should use that.
