### ISSUE TITLE
Replace duplicate code in GitHub actions

### ISSUE THREAD

**Issue by beerparty** [kubearchive/kubearchive#220]
There is a bunch of duplicate code in the GitHub actions. This code should be refactored with one of the techniques explained in this GitHub DRY (Don't Repeat Yourself) article:: https://cardinalby.github.io/blog/post/github-actions/dry-reusing-code-in-github-actions/ (or other similar technique).

The actions also include a bunch of debug right at the beginning of the action - we should determine if that should remain.

**Comment by rh-hemartin** [comment]
We need to talk about what things we don't want to repeat, because it is just normal that they repeat. The moment we start to not repeat ourselves is the moment we lose flexibility. Then we would need that flexibility, so instead of taking a step back into repeating and gaining flexibility locally, we will introduce a conditional because we want to keep not repeating. Then we would need another conditional, and another, etc. I'm being overly dramatic, but I think it makes my point clearer.

**Comment by rh-hemartin** [comment]
About the debug information I think it should go away, we don't want the complexity of not repeating because of some information that is already printed elsewhere, see my reasoning in this comment https://github.com/kubearchive/kubearchive/pull/204#discussion_r1686535911.

**Comment by maruiz93** [comment]
> We need to talk about what things we don't want to repeat, because it is just normal that they repeat. The moment we start to not repeat ourselves is the moment we lose flexibility. Then we would need that flexibility, so instead of taking a step back into repeating and gaining flexibility locally, we will introduce a conditional because we want to keep not repeating. Then we would need another conditional, and another, etc. I'm being overly dramatic, but I think it makes my point clearer.

Usually the point of following the DRY principle is to increase maintainability:

* If we want to modify/remove something that is repeated in several places, it's easy to miss one
* If we have something (like workflows in this case) that we want to enforce having a repeated code (a initial step in this case) it's easier to miss adding this repeated piece
* When we repeat ourselves we make the codebase larger and sometimes that means less readable

I think that wondering if we should apply a mechanism to Don't Repeat Ourselves is a good thing because sometimes the mechanism is not worth the effort but I think that many other times it is.

@rh-hemartin Do you have any particular example or any specific reason to avoid reusing workflows or part of workflows in Github Actions?

**Comment by rh-hemartin** [comment]
> @rh-hemartin Do you have any particular example or any specific reason to avoid reusing workflows or part of workflows in Github Actions?

Given the article linked I don't see any other option than creating an actions repository, and that is something I would like to avoid.

**Comment by maruiz93** [comment]
IIUC, going with the "Composite Actions" doesn't imply having the actions in a separate repository, take a look at [this example repo](https://github.com/UCL/composite-actions) where actions and workflows live in the same repo.

For the particular example of reusing a `step` I agree that composite actions would be the best fit, but for other situation in which we want to reuse a whole `job` (a sequence of steps) I think that we might want to consider the reusable workflows. Here is [another repo](https://github.com/vegardit/haxe-reusable-workflows/tree/v1) I found with examples of both reusable workflows and actions in the same repo.

Of course, if in the future we end up having a lot of Github actions and workflows and we want to have them in a separate repo, like they do in [knative](https://github.com/knative/actions), we can, but there are no enforcement to do so. 

I believe both reusable workflows and composite actions are pretty common.

**Comment by rh-hemartin** [comment]
If we can use composite actions on the same repository then its not that dramatic. I guess then its `use: ./.github/composites/step-x` and then have `.github/composites/step-x/action.yml`.

**Comment by beerparty** [comment]
> About the debug information I think it should go away, we don't want the complexity of not repeating because of some information that is already printed elsewhere, see my reasoning in this comment [#204 (comment)](https://github.com/kubearchive/kubearchive/pull/204#discussion_r1686535911).

I disagree with removing the debug information. I realize that the information is available in other places, but I want all that information in a single place in the logs where it will be easy to find when we are debugging issues. Once it is refactored so that this logging code is in one place (likely with a composite action), maintaining it will be easier. I expect to add additional information in this section, so all the necessary configuration information we want to see will be available in one place for every CI job we run.

**Comment by ggallen** [comment]
> We need to talk about what things we don't want to repeat, because it is just normal that they repeat. The moment we start to not repeat ourselves is the moment we lose flexibility.

I think we are past this already, but I don't understand this statement.

Using your logic, you would be against looping?  I know, it's an extreme case, but you presented and extreme case as well! And it's late on Friday!

**Comment by rh-hemartin** [comment]
> I think we are past this already, but I don't understand this statement.

Let's move this another forum. If you want to follow it up, ping me.
