### ISSUE TITLE
Add "unparam" to golangci linters

### ISSUE THREAD

**Issue by rh-hemartin** [kubearchive/kubearchive#365]
Golangci has this linter called "unparam" which helps with unused parameters on functions. I think that by default Go complains about unused variables that are defined on the function, but not about parameters. This linter should help us when refactoring to make sure that every parameter is being used.

**Comment by maruiz93** [comment]
I don't think we should add this in our CI.

We have unused parameters in functions that make "fake" resources for testing because the are implementing an interface in a dummy way (and they don't use all the parameters):
* `opts` in [fakeTokenReview Create](https://github.com/kubearchive/kubearchive/blob/main/cmd/api/auth/authn_test.go#L30)
* `opts` in [fakeSubjectAccessReview Create](https://github.com/kubearchive/kubearchive/blob/main/cmd/api/auth/authz_test.go#L32)
* `ctx` in fake [Database](https://github.com/kubearchive/kubearchive/blob/main/pkg/database/fake/database_generated.go#L21) methods

**Comment by rh-hemartin** [comment]
I think we can't rely on users having things properly configured. As we can see in #342 thanks to the CI we can see that the author didn't run `goimports` on their local machine before pushing. 

Regarding the linter `unparam`, it tries to minimize false positives and all of those are covered: check https://github.com/mvdan/unparam

> To minimise false positives, it ignores certain cases such as:
>
>    Exported functions (by default, see -exported)
>    Unnamed and underscore parameters (like _ and _foo)
>    Funcs that may satisfy an interface
>    Funcs that may satisfy a function signature
>    Funcs that are stubs (empty, only error, immediately return, etc)
>    Funcs that have multiple implementations via build tags

So those won't be raised as problems. In fact I run it locally and it didn't point me to any false positive.

**Comment by maruiz93** [comment]
oh, then I take back what I said and I'm good to go with configuring `unused` check in the CI
