### ISSUE TITLE
Add `namespace` to resources in Helm templates

### ISSUE THREAD

**Issue by rh-hemartin** [kubearchive/kubearchive#371]
The mechanism of releasing, at #328, creates a single YAML for release that is created using `helm template`. The resources on this YAML do not work if installed on any other namespace, so the #274 will force users to run `kubectl apply -f kubearchive.yaml -n kubearchive` so KubeArchive works properly. This potential error can be fixed introducing the `namespace` metadata in the resources on the Helm chart.

**Acceptance Criteria**

* Add `namespace` to all resources in the Helm chart that need it  (that are not Cluster wide resources)
* Add `namespace` to the resources that the `cmd/operator/generate.sh` generates

**Comment by maruiz93** [comment]
This is related to https://github.com/helm/helm/issues/3553 where is discussed why `helm template` doesn't act the same way as `helm install` by including the `namespace` field in the matadata when provided on the command.

Maybe this issue is addressed in future helm versions, but for now, I think that it's a good idea to enforce the appearance of the `metadata.namespace` field in the different resources of the chart.

**Comment by ggallen** [comment]
>  The resources on this YAML do not work if installed on any other namespace

Why is this?

**Comment by rh-hemartin** [comment]
> > The resources on this YAML do not work if installed on any other namespace
> 
> Why is this?

The problems I found are: webhook location namespace is kubearchive in the CRD, clusterrolebindings point to the service account on the namespace kubearchive, etc. It makes sense, as these should be filled.

Most Kubernetes products out there ask you to create a specific namespace and install using it or create their own. We will ask the user to install in a certain namespace, but we may want to force it ourselves inside the YAML so its less prone to errors.
