### ISSUE TITLE
Investigate Replacing `db.QueryPerformer` with `sqlx.SelectContext`

### ISSUE THREAD

**Issue by skoved** [kubearchive/kubearchive#634]
[`sqlx.SelectContext`](https://pkg.go.dev/github.com/jmoiron/sqlx#SelectContext) will populate a slice of any type based on a `SELECT` sql statement and attempt to convert each row of the database into a struct. From what I can see, the type of the slice needs to be compatible with the fields that you are returning from the database. The [`usage`](https://pkg.go.dev/github.com/jmoiron/sqlx#readme-usage) section has an example using `sqlx.Select` with a Person struct.

**Comment by rh-hemartin** [comment]
As we are discussing on #504 we may not need this.

**Comment by maruiz93** [comment]
> Just to keep it in mind: we are discussing on https://github.com/kubearchive/kubearchive/issues/504 we may not need this.

I think it's not related. They are different discussions.
This issue is for handling parsing the rows into manageable structs, but it doesn't imply having the jsonb fields deserialized into the `Unstructured` structs, we may just want to have a struct with the fields: `id`, `created_at` and `data` (as a string).
