### ISSUE TITLE
Enable YAML linting for helm files

### ISSUE THREAD

**Issue by rh-hemartin** [kubearchive/kubearchive#67]
Currently most of our Helm files are disabled for yamllint linting. We should remove the ignore lines and make sure those files are in line with the yamllint linter. The files that exist on `crds` should be ignored, as they are dependencies that we do not control and don't want to fix for correctness.

**Comment by rh-hemartin** [comment]
It is worth to mention that currently yamllint does not like `{{ variable }}` and that instead wants `{{variable}}`. I think the prefer the first, as everyone wrote the YAML files that way, so we should change the configuration a bit.

**Comment by skoved** [comment]
also `{{ variable }}` with the space is the preferred helm syntax

**Comment by maruiz93** [comment]
AFAIK, we are already addressing this although we are including `charts/kubearchive` to be ignored in the `.yamllint` config file (see [this line](https://github.com/kubearchive/kubearchive/blob/main/.yamllint.yml#L6)). 
In the `static-code-analysis` [action](https://github.com/kubearchive/kubearchive/blob/main/.github/workflows/static_code_analysis.yml), we are doing the following:

1. `ct lint`
2. `helm template`  saving the output in `charts/generated/`
3. run `yamllint` --> this will run on the charts/generated new directory with all the templated files, so I believe we are covered in that regard, and we don't need to worry about the `{{ variable }}` or `{{variable}}` spacing because we are linting the templated final files and not the templates with the variables.

**Comment by rh-hemartin** [comment]
Implemented in #87

**Comment by rh-hemartin** [comment]
Implemented in #87
