### ISSUE TITLE
cli can get resources from kubearchive database

### ISSUE THREAD

**Issue by skoved** [kubearchive/kubearchive#79]
The cli can call appropriate endpoints provided by the api server to print out archived resources. Related to #78

**Comment by rh-hemartin** [comment]
I'm starting to explore this, the first thing I noticed is that I need to expose the API to query it from the CLI. Port-forward works OK, but I'm also exploring an ingress.

**Comment by rh-hemartin** [comment]
I'm trying different approaches.

One of them is to mimic what kubectl get does, which is to use a resource.Builder that has a nice-ish interface to build the query and send it. I can use that to reach both the K8S api server and k9e api server. The first stopper is that it does not automatically adds the bearer token when reaching for the server. It also reaches first to /api/ to get a list of things available. So that means that we will need to implement more endpoints, even if they just redirect to the k8s api server.

The other approach I am trying is to use a normal http client, but then I need to build the URL myself, which falls under the same problem again: /api/ vs /apis/, pluralizing names, and getting apiversions.

I'm currently leaning towards the simple http.Client even if we need to pluralize names, or be more strict with what the user provides.
